---
- name: "Creating destination directory"
  file:
    path: "{{ webserver.ospath }}/uuid/{{ inventory_hostname }}/"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: 'Templating out boot script for targets with template "esxi/7.0U2a"'
  template:
    src:  "{{ webserver.ospath }}/uuid/{{ inventory_hostname }}/{{ item }}.j2"
    dest: "{{dst_dir}}{{ item }}"
    owner: www-data
    group: www-data
    mode: '0644'
  loop:
    - script.ipxe
    - boot.cfg
    - ks.cfg