---
- name: Mounting ESXi 6.7U3b ISO
  ansible.posix.mount:
    path: "{{ webserver.ospath }}/shared/esxi/6.7U3b/"
    src: "{{ iso.ospath }}/VMware-VMvisor-Installer-201912001-15160138.x86_64.iso"
    fstype: iso9660
    state: mounted